apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ix2h5k7j1-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ix2h5k7j1-java-quarkus-gitops