apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ix2h5k7j1-java-quarkus
  janus-idp.io/tekton: ix2h5k7j1-java-quarkus
  backstage.io/kubernetes-id: ix2h5k7j1-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ix2h5k7j1-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
